Syslog              yes
# This is the ID this server uses to sign its own results
AuthservID          mail.myreceiver.com
# This is the list of IDs we trust results from
TrustedAuthservIDs  mail.myreceiver.com
RejectFailures      true
SPFSelfValidate true
RequiredHeaders true