Syslog          yes
# Mode 'v' = verify only
Mode            v
Socket              inet:8891@localhost
Nameservers 192.168.56.10
RequiredHeaders true
# We don't need keys or tables on the receiver side