Syslog          yes
UMask           007
# Mode 's' = sender/signer
Mode            sv
Canonicalization relaxed/simple
ExternalIgnoreList  refile:/etc/opendkim/trusted.hosts
InternalHosts       refile:/etc/opendkim/trusted.hosts
KeyTable            refile:/etc/opendkim/key.table
SigningTable        refile:/etc/opendkim/signing.table
Socket              inet:8891@localhost
Nameservers 127.0.0.1